spring.application.name=myapp
spring.data.mongodb.database=journaldb
# FOR LOCAL CONNECTION
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root
# FOR MONGODB ATLAS
spring.data.mongodb.uri=mongodb+srv://akashmurumkar:QSS9gltvYV4OngrN@cluster0.hwyayk5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# For Auto Indexing the Collection
spring.data.mongodb.auto-index-creation=true